-- Table to store Movie information on an ORACLE database
CREATE TABLE MOVIES
(
    ID                  NUMBER
        GENERATED AS IDENTITY PRIMARY KEY,
    TMDB_MOVIE_ID       NUMBER
        CONSTRAINT NN_MOVIES_TMDB_MOVIE_ID NOT NULL
        CONSTRAINT UN_MOVIES_TMDB_MOVIE_ID UNIQUE,
    TITLE               VARCHAR2(255)
        CONSTRAINT NN_MOVIES_TITLE NOT NULL,
    VOTE_AVERAGE        NUMBER(4, 1)
        CONSTRAINT CH_VOTE_AVERAGE CHECK (VOTE_AVERAGE BETWEEN 0 AND 10),
    RELEASE_DATE        DATE,
    DURATION_IN_SECONDS NUMBER
        CONSTRAINT CH_DURATION_IN_SECONDS CHECK (DURATION_IN_SECONDS >= 0),
    ORIGINAL_TITLE      VARCHAR2(255),
    ORIGINAL_LANGUAGE   VARCHAR2(30),
    IMAGE_PATH          VARCHAR2(255),
    BUDGET              NUMBER(20, 2)
);